title: Project Journal
author: bryce rowe
email: bjrowedev@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
 This blog will detail my journey at my workplacement at blueberry IT
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: /texture

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Bryce Rowe
  tagline: Be Good
  date_format: "%b %-d, %Y"
  style: green
  showNav: false
  showPicker: false

  # generate social links in footer
  social_links:
  #  twitter: thelehhman
  #  github:  thelehhman
  # linkedIn: in/thelehhman
  #  rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
